# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00' # UTC
    target-branch: 'main'
    versioning-strategy: 'increase-if-necessary'
    open-pull-requests-limit: 10
    groups:
      vite:
        patterns:
          - 'vite'
          - 'vitest'
          - '@vitest/*'
          - '@vitejs/*'
          - 'vite-*'
          - 'jsdom'
      metamask:
        patterns:
          - '@metamask/*'
        exclude-patterns:
          - '@metamask/eslint-*'
      metamask-eslint:
        patterns:
          - '@metamask/eslint-*'
      agoric:
        patterns:
          - '@agoric/*'
          - '@endo/*'
          - 'ses'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
      typescript:
        patterns:
          - 'typescript'
          - 'typescript-*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'
      testing-library:
        patterns:
          - '@testing-library/*'
      playwright:
        patterns:
          - '@playwright/*'
          - 'playwright'
