name: Lint, Build, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: ${{ matrix.node-version == '22.x' }}
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn lint
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn changelog:validate
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn build
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Rebuild SQLite3
        run: |
          cd node_modules/better-sqlite3
          yarn build-release
          cd -
      - run: yarn build
      - run: yarn test:ci
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn test:integration
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Rebuild SQLite3
        run: |
          cd node_modules/better-sqlite3
          yarn build-release
          cd -
      - run: VITE_DB_FOLDER=e2e yarn build
      - name: Run E2E tests
        id: e2e
        run: yarn test:e2e:ci
      - name: Upload test artifacts
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: packages/extension/test-results
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
